// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Rlf1Hd-ph0vR09AIHrx4j51WgZs2uhw',
    appId: '1:1042591431547:web:0d9443abf5cde4e2065bde',
    messagingSenderId: '1042591431547',
    projectId: 'evo-finder-f6c9e',
    authDomain: 'evo-finder-f6c9e.firebaseapp.com',
    storageBucket: 'evo-finder-f6c9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY1NvM6liEjjy0COrM4IMBxUOIsS0GZlY',
    appId: '1:1042591431547:android:6123dcdbc424808e065bde',
    messagingSenderId: '1042591431547',
    projectId: 'evo-finder-f6c9e',
    storageBucket: 'evo-finder-f6c9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtWGRQvhByL6kqFbIKBQN1NIKd_eTTUQU',
    appId: '1:1042591431547:ios:cc9fdc507e49eb8b065bde',
    messagingSenderId: '1042591431547',
    projectId: 'evo-finder-f6c9e',
    storageBucket: 'evo-finder-f6c9e.appspot.com',
    iosBundleId: 'com.example.evoFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtWGRQvhByL6kqFbIKBQN1NIKd_eTTUQU',
    appId: '1:1042591431547:ios:cc9fdc507e49eb8b065bde',
    messagingSenderId: '1042591431547',
    projectId: 'evo-finder-f6c9e',
    storageBucket: 'evo-finder-f6c9e.appspot.com',
    iosBundleId: 'com.example.evoFinder',
  );
}
